### ISSUE TITLE
is:issue is:open Copy .env.example file to .env and edit database credentials there

### ISSUE THREAD

**Issue by sawepeter** [csesumonpro/laravel-vus-js-super-blog#1]
what is the correct process of doing this.I have cloned the project but am confused here.

**Comment by csesumonpro** [comment]
yes, it's the right way because when you working with stripe payment or PayPal payment or any other secret key. We are always put in different secret keys in .env file that's why any developer can't publish .env file even git automatically ignore .env file to push in Github. but if you want to publish it you can do this.  I hope you are cleared.
